Controllers/ReportApiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Angular.ReportBuilder.Models;

namespace Angular.ReportBuilder.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class ReportApiController : ControllerBase
    {
        public DotNetReportSettings GetSettings()
        {
            var settings = new DotNetReportSettings
            {
                ApiUrl = Startup.StaticConfig.GetValue<string>("dotNetReport:apiUrl"),
                AccountApiToken = Startup.StaticConfig.GetValue<string>("dotNetReport:accountApiToken"), // Your Account Api Token from your http://dotnetreport.com Account
                DataConnectApiToken = Startup.StaticConfig.GetValue<string>("dotNetReport:dataconnectApiToken") // Your Data Connect Api Token from your http://dotnetreport.com Account
            };

            // Populate the values below using your Application Roles/Claims if applicable

            settings.ClientId = "";  // You can pass your multi-tenant client id here to track their reports and folders
            settings.UserId = ""; // You can pass your current authenticated user id here to track their reports and folders            
            settings.UserName = "";
            settings.CurrentUserRole = new List<string>(); // Populate your current authenticated user's roles

            settings.Users = new List<string>(); // Populate all your application's user, ex  { "Jane", "John" }
            settings.UserRoles = new List<string>(); // Populate all your application's user roles, ex  { "Admin", "Normal" }       
            settings.CanUseAdminMode = true; // Set to true only if current user can use Admin mode to setup reports and dashboard

            return settings;
        }
        
        [HttpPost]
        public IActionResult GetLookupList(dynamic model)
        {
            string lookupSql = model.lookupSql;
            string connectKey = model.connectKey;

            var sql = DotNetReportHelper.Decrypt(lookupSql);

            // Uncomment if you want to restrict max records returned
            sql = sql.Replace("SELECT ", "SELECT TOP 500 ");

            var dt = new DataTable();
            using (var conn = new SqlConnection(Startup.StaticConfig.GetConnectionString(connectKey)))
            {
                conn.Open();
                var command = new SqlCommand(sql, conn);
                var adapter = new SqlDataAdapter(command);

                adapter.Fill(dt);
            }

            var data = new List<object>();
            foreach (DataRow dr in dt.Rows)
            {
                data.Add(new { id = dr[0], text = dr[1] });
            }

            return Ok(data);
        }

        [HttpPost]
        public async Task<IActionResult> RunReportApi(DotNetReportApiCall data)
        {
            return await CallReportApi(data.Method, JsonConvert.SerializeObject(data));
        }

        [HttpGet]
        public async Task<IActionResult> CallReportApi(string method, string model)
        {
            using (var client = new HttpClient())
            {
                var settings = GetSettings();
                var keyvalues = new List<KeyValuePair<string, string>>
                {
                    new KeyValuePair<string, string>("account", settings.AccountApiToken),
                    new KeyValuePair<string, string>("dataConnect", settings.DataConnectApiToken),
                    new KeyValuePair<string, string>("clientId", settings.ClientId),
                    new KeyValuePair<string, string>("userId", settings.UserId),
                    new KeyValuePair<string, string>("userRole", String.Join(",", settings.CurrentUserRole))
                };

                var data = JsonConvert.DeserializeObject<Dictionary<string, dynamic>>(model);
                foreach (var key in data.Keys)
                {
                    if (key != "adminMode" || (key == "adminMode" && settings.CanUseAdminMode))
                    {
                        keyvalues.Add(new KeyValuePair<string, string>(key, data[key].ToString()));
                    }
                }

                var content = new FormUrlEncodedContent(keyvalues);
                var response = await client.PostAsync(new Uri(settings.ApiUrl + method), content);
                var stringContent = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject(stringContent);                
                if (stringContent == "\"\"") result = new {};
                return Ok(result);
            }

        }

        [HttpPost]
        public IActionResult RunReport(dynamic data)
        {
            string reportSql = data.reportSql;
            string connectKey = data.connectKey;
            string reportType = data.reportType;
            int pageNumber = 1;
            int pageSize = 50;
            string sortBy = data.sortBy;
            bool desc = data.desc;


            var sql = DotNetReportHelper.Decrypt(HttpUtility.HtmlDecode(reportSql));

            try
            {
                if (!String.IsNullOrEmpty(sortBy))
                {
                    if (sortBy.StartsWith("DATENAME(MONTH, "))
                    {
                        sortBy = sortBy.Replace("DATENAME(MONTH, ", "MONTH(");
                    }
                    if (sortBy.StartsWith("MONTH(") && sortBy.Contains(")) +") && sql.Contains("Group By"))
                    {
                        sortBy = sortBy.Replace("MONTH(", "CONVERT(VARCHAR(3), DATENAME(MONTH, ");
                    }
                    sql = sql.Substring(0, sql.IndexOf("ORDER BY")) + "ORDER BY " + sortBy + (desc ? " DESC" : "");
                }

                // Execute sql
                var dt = new DataTable();
                var dtPaged = new DataTable();
                using (var conn = new SqlConnection(Startup.StaticConfig.GetConnectionString(connectKey)))
                {
                    conn.Open();
                    var command = new SqlCommand(sql, conn);
                    var adapter = new SqlDataAdapter(command);

                    adapter.Fill(dt);
                }

                dtPaged = (dt.Rows.Count > 0) ? dtPaged = dt.AsEnumerable().Skip((pageNumber - 1) * pageSize).Take(pageSize).CopyToDataTable() : dt;

                var model = new DotNetReportResultModel
                {
                    ReportData = DataTableToDotNetReportDataModel(dtPaged, sql),
                    Warnings = GetWarnings(sql),
                    ReportSql = sql,
                    ReportDebug = Request.Host.Host.Contains("localhost"),
                    Pager = new DotNetReportPagerModel
                    {
                        CurrentPage = pageNumber,
                        PageSize = pageSize,
                        TotalRecords = dt.Rows.Count,
                        TotalPages = (int)((dt.Rows.Count / pageSize) + 1)
                    }
                };

                return Ok(model);

            }

            catch (Exception ex)
            {
                var model = new DotNetReportResultModel
                {
                    ReportData = new DotNetReportDataModel(),
                    ReportSql = sql,
                    HasError = true,
                    Exception = ex.Message
                };

                return Ok(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetDashboards(bool adminMode = false)
        {
            var model = await GetDashboardsData(adminMode);
            return Ok(model);
        }

        public async Task<dynamic> GetDashboardsData(bool adminMode = false)
        {
            var settings = GetSettings();

            using (var client = new HttpClient())
            {
                var content = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("account", settings.AccountApiToken),
                    new KeyValuePair<string, string>("dataConnect", settings.DataConnectApiToken),
                    new KeyValuePair<string, string>("clientId", settings.ClientId),
                    new KeyValuePair<string, string>("userId", settings.UserId),
                    new KeyValuePair<string, string>("userRole", String.Join(",", settings.CurrentUserRole)),
                    new KeyValuePair<string, string>("adminMode", adminMode.ToString()),
                });

                var response = await client.PostAsync(new Uri(settings.ApiUrl + $"/ReportApi/GetDashboards"), content);
                var stringContent = await response.Content.ReadAsStringAsync();

                var model = JsonConvert.DeserializeObject<dynamic>(stringContent);
                return model;
            }
        }
        
        [HttpGet]
        public IActionResult GetUsersAndRoles()
        {
            var settings = GetSettings();
            return Ok(new
            {
                noAccount = string.IsNullOrEmpty(settings.AccountApiToken) || settings.AccountApiToken == "Your Public Account Api Token",
                users = settings.CanUseAdminMode ? settings.Users : new List<string>(),
                userRoles = settings.CanUseAdminMode ? settings.UserRoles : new List<string>(),
                currentUserId = settings.UserId,
                currentUserRoles = settings.UserRoles,
                currentUserName = settings.UserName,
                allowAdminMode = settings.CanUseAdminMode
            });
        }

        private string GetWarnings(string sql)
        {
            var warning = "";

Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Angular.ReportBuilder.Models;

namespace Angular.ReportBuilder.Controllers
{
    public class ReportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Report(int reportId, string reportName, string reportDescription, bool includeSubTotal, bool showUniqueRecords,
            bool aggregateReport, bool showDataWithGraph, string reportSql, string connectKey, string reportFilter, string reportType, int selectedFolder)
        {
            var model = new DotNetReportModel
            {
                ReportId = reportId,
                ReportType = reportType,
                ReportName = HttpUtility.UrlDecode(reportName),
                ReportDescription = HttpUtility.UrlDecode(reportDescription),
                ReportSql = reportSql,
                ConnectKey = connectKey,
                IncludeSubTotals = includeSubTotal,
                ShowUniqueRecords = showUniqueRecords,
                ShowDataWithGraph = showDataWithGraph,
                SelectedFolder = selectedFolder,
                ReportFilter = reportFilter // json data to setup filter correctly again
            };

            return View(model);
        }

        public async Task<IActionResult> Dashboard(int? id = null, bool adminMode = false)
        {
            var reportApi = new ReportApiController();
            var model = new List<DotNetDasboardReportModel>();
            var settings = reportApi.GetSettings();

            var dashboards = (JArray)(await reportApi.GetDashboardsData(adminMode));
            if (!id.HasValue && dashboards.Count > 0)
            {
                id = ((dynamic)dashboards.First()).Id;
            }

            using (var client = new HttpClient())
            {
                var content = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("account", settings.AccountApiToken),
                    new KeyValuePair<string, string>("dataConnect", settings.DataConnectApiToken),
                    new KeyValuePair<string, string>("clientId", settings.ClientId),
                    new KeyValuePair<string, string>("userId", settings.UserId),
                    new KeyValuePair<string, string>("userRole", String.Join(",", settings.CurrentUserRole)),
                    new KeyValuePair<string, string>("id", id.HasValue ? id.Value.ToString() : "0"),
                    new KeyValuePair<string, string>("adminMode", adminMode.ToString()),
                });

                var response = await client.PostAsync(new Uri(settings.ApiUrl + $"/ReportApi/LoadSavedDashboard"), content);
                var stringContent = await response.Content.ReadAsStringAsync();

                model = JsonConvert.DeserializeObject<List<DotNetDasboardReportModel>>(stringContent);
            }

            return View(new DotNetDashboardModel
            {
                Dashboards = dashboards.Select(x => (dynamic)x).ToList(),
                Reports = model
            });
        }

        [HttpPost]
        public IActionResult DownloadExcel(string reportSql, string connectKey, string reportName)
        {
            var excel = DotNetReportHelper.GetExcelFile(reportSql, connectKey, reportName);
            Response.Headers.Add("content-disposition", "attachment; filename=" + reportName + ".xlsx");
            Response.ContentType = "application/vnd.ms-excel";
            
            return File(excel, "application/vnd.ms-excel", reportName + ".xlsx");
        }

        [HttpPost]
        public IActionResult DownloadXml(string reportSql, string connectKey, string reportName)
        {
            var xml = DotNetReportHelper.GetXmlFile(reportSql, connectKey, reportName);
            Response.Headers.Add("content-disposition", "attachment; filename=" + reportName + ".xml");
            Response.ContentType = "application/xml";

            return File(xml, "application/xml", reportName + ".xml");
        }

    }
}

Views/Report/Dashboard.cshtml
@using System.Configuration
@model Angular.ReportBuilder.Models.DotNetDashboardModel
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/shared/_Layout.Report.cshtml";
}

@section head {
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/gridstack.js/0.4.0/gridstack.min.css" />
}

@section scripts{
    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/gridstack.js/0.4.0/gridstack.min.js'></script>
    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/gridstack.js/0.4.0/gridstack.jQueryUI.min.js'></script>
    <script type="text/javascript">
    $(document).ready(function () {
        var reports = [];
        var dashboards = [];

        @foreach (var d in Model.Dashboards)
        {
        @:dashboards.push({ id: @d.Id, name: "@d.Name", description: "@d.Description", selectedReports: "@d.SelectedReports", userId: "@d.UserId", userRoles: "@d.UserRoles", viewOnlyUserId: "@d.ViewOnlyUserId", viewOnlyUserRoles: "@d.ViewOnlyUserRoles"  });
        }

        @foreach (var r in Model.Reports)
        {
        @:reports.push({ reportSql: "@r.ReportSql", reportId: @r.ReportId, reportFilter: htmlDecode('@System.Web.HttpUtility.UrlDecode(r.ReportFilter)'), connectKey: "@r.ConnectKey", x: @r.X, y: @r.Y, width: @r.Width, height: @r.Height });
        }

        ajaxcall({ url: '@Url.Action("GetUsersAndRoles", "ReportApi")' }).done(function (data) {
            var vm = new dashboardViewModel({
                runReportUrl: "@Url.Action("Report")",
                execReportUrl: "@Url.Action("RunReport", "ReportApi")",
                reportWizard: $("#filter-panel"),
                lookupListUrl: "@Url.Action("GetLookupList", "ReportApi")",
                apiUrl: "@Url.Action("CallReportApi", "ReportApi")",
                runReportApiUrl: "@Url.Action("RunReportApi", "ReportApi")",
                reportMode: "execute",
                reports: reports,
                dashboards: dashboards,
                users: data.users,
                userRoles: data.userRoles,
                allowAdmin: data.allowAdminMode,
                dashboardId: @(Context.Request.Query["id"].Any() ? Context.Request.Query["id"].First() : "0")
            });

            vm.init().done(function () {
                ko.applyBindings(vm);
                $(function () {
                    var options = {
                        cellHeight: 80,
                        verticalMargin: 10
                    };
                    $('.grid-stack').gridstack(options);
                    //$(".list-overflow-auto").each(function () {
                    //    $(this).css('height', $(this).height() - 10);
                    //});
                    $('.grid-stack').on('gsresizestop', function (event, elem) {
                        var newHeight = $(elem).attr('data-gs-height');
                        $(elem).closest(".list-overflow-auto").css('height', newHeight - 50);
                    });
                    $('.grid-stack').on('change', function (event, items) {
                        _.forEach(items, function (x) {
                            vm.updatePosition(x);
                        });
                    });
                });
            });

            $(window).resize(function () {
                vm.drawChart();
            });
        });
    });
    </script>
}

<div class="row">
    <div class="col-8" data-bind="with: currentDashboard">
        <h2 data-bind="text: name ? name : 'Dashboard'">Dashboard</h2>
        <p data-bind="text: description"></p>
    </div>

    <div class="col-4 right-align" style="display: none;" data-bind="visible: dashboards().length > 0 ">
        <div class="row">

            <label class="col">Switch Dashboard</label>
            <select class="col form-control" data-bind="options: dashboards, optionsText: 'name', optionsValue: 'id', value: selectDashboard"></select>
            <div class="col">
                <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#add-dashboard-modal" title="Edit Dashboard Settings" data-bind="click: editDashboard">Edit</button>
                <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#add-dashboard-modal" title="Add a New Dashboard" data-bind="click: newDashboard">Add</button>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>

<div data-bind="template: {name: 'admin-mode-template'}, visible: allowAdmin" style="display: none;"></div>

<div class="alert alert-info">
    To manage Reports, please <a href="@Url.Action("Index","Report")">click here</a>.
</div>
<div class="centered" style="display: none;" data-bind="visible: dashboards().length == 0 ">
    No Dashboards yet. Click below to Start<br />
    <button class="btn btn-lg btn-primary" data-toggle="modal" data-target="#add-dashboard-modal"><i class="fa fa-dashboard"></i> Create a New Dashboard</button>
</div>

<div class="modal modal-fullscreen" id="add-dashboard-modal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" data-bind="with: dashboard">
            <div class="modal-header">
                <h4 class="modal-title"><span data-bind="text: Id() ? 'Edit' : 'Add'"></span> Dashboard</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="control-group">
                        <div class="form-group row">
                            <label class="col-md-3 col-sm-3 control-label">Name</label>
                            <div class="col-md-6 col-sm-6">
                                <input class="form-control text-box" style="width: 100%;" data-val="true" data-val-required="Dashboard Name is required." type="text" data-bind="value: Name" placeholder="Dashboard Name, ex Sales, Accounting" id="add-dash-name" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-sm-3 control-label">Description</label>
                            <div class="col-md-6 col-sm-6">
                                <textarea class="form-control text-box" style="width: 100%;" data-bind="value: Description" placeholder="Optional Description for the Dashboard">
                                </textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <hr />
                <h5><span class="fa fa-paperclip"></span> Choose Reports for the Dashboard</h5>
                <div data-bind="foreach: $parent.reportsAndFolders" class="card" style="margin-left: 20px;">
                    <div class="card-body">
                        <a class="btn btn-link" role="button" data-toggle="collapse" data-bind="attr: {href: '#folder-' + folderId }">
                            <i class="fa fa-folder"></i>&nbsp;<span data-bind="text: folder"></span>
                        </a>
                        <div class="collapse" data-bind="attr: {id: 'folder-' + folderId }">
                            <ul class="list-group" data-bind="foreach: reports">
                                <li class="list-group-item">
                                    <div class="checkbox">
                                        <label class="list-group-item-heading">
                                            <input type="checkbox" data-bind="checked: selected">
                                            <span class="fa" data-bind="css: {'fa-file': reportType=='List', 'fa-th-list': reportType=='Summary', 'fa-bar-chart': reportType=='Bar', 'fa-pie-chart': reportType=='Pie',  'fa-line-chart': reportType=='Line', 'fa-globe': reportType =='Map'}" style="font-size: 14pt; color: #808080"></span>
                                            <span data-bind="text: reportName"></span>
                                        </label>
                                    </div>
                                    <p class="list-group-item-text small" data-bind="text: reportDescription"></p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- ko if: $parent.adminMode -->
                <hr />
                <div data-bind="template: {name: 'manage-access-template'}"></div>
                <!-- /ko -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bind="click: $root.deleteDashboard, visible: Id">Delete Dashboard</button>
                <button type="button" class="btn btn-primary" data-bind="click: $root.saveDashboard">Save Dashboard</button>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>

<div class="grid-stack">
    <!-- ko foreach: reports -->
    <div class="grid-stack-item" data-bind="attr: {'data-gs-x': x, 'data-gs-y': y, 'data-gs-width': width, 'data-gs-height': height, 'data-gs-auto-position': true, 'data-gs-id': ReportID}">

        <div class="card" data-bind="attr: {class: 'card ' + panelStyle + ' grid-stack-item-content'}" style="overflow-y: hidden;">
            <div class="card-header">
                <span data-bind="text: ReportName"></span>
                <div class="pull-right">
                    @using (Html.BeginForm("DownloadExcel", "Report", FormMethod.Post))
                    {
                        <input type="hidden" id="reportSql" name="reportSql" data-bind="value: currentSql" />
                        <input type="hidden" id="connectKey" name="connectKey" data-bind="value: currentConnectKey" />
                        <input type="hidden" id="reportName" name="reportName" data-bind="value: ReportName" />
                        <button type="submit" class="btn btn-secondary btn-sm"><span class="fa fa-file-excel-o"></span></button>
                    }
                </div>
                <!-- ko if: FlyFilters().length> 0-->
                <button class="btn btn-secondary btn-sm pull-right" data-bind="click: toggleFlyFilters"><i class="fa fa-filter" title="Filter Report"></i></button>
                <!-- /ko -->

                <a data-bind="attr: {href: '@Url.Action("Index","Report")?reportId=' + ReportID()}" class="btn btn-secondary btn-sm pull-right">
                    <i class="fa fa-pencil-square-o" title="Edit Report"></i>
                </a>
            </div>
            <div class="card-body list-overflow-auto">
                <p data-bind="html: ReportDescription">
                </p>
                <div data-bind="template: {name: 'fly-filter-template'}, visible: showFlyFilters"></div>
                <div data-bind="with: ReportResult">
                    <div data-bind="template: 'report-template', data: $data"></div>
                </div>
            </div>
            <div class="card-footer">
                <div class="small" data-bind="with: pager">
                    <div class="form-group pull-left total-records">
                        <span data-bind="text: 'Total Records: ' + totalRecords()"></span><br />
                    </div>
                    <div class="form-group pull-right" data-bind="if: pages()>1">
                        <div data-bind="template: 'pager-template', data: $data"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>

    </div>
    <!-- /ko -->
</div>